name : First Workflow

on :
  push:
    - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo"Welcome to our first GitHub Actions Workflow!"
